package app.recipebook.data.local.shoppinglist

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class ShoppingListLocalModelsTest {

    @Test
    fun codec_roundTrip_preservesState() {
        val state = ShoppingListState(
            sections = listOf(
                ShoppingSection(id = "produce", name = "Produce", sortOrder = 0),
                ShoppingSection(id = "custom", name = "Asian Market", sortOrder = 1)
            ),
            entries = listOf(
                ShoppingListEntry(
                    id = "entry-1",
                    name = "Chickpeas",
                    amount = "2 cans",
                    sectionId = "pantry",
                    checked = false,
                    isAutoGenerated = true,
                    sourceRecipeId = "recipe-1",
                    sourceIngredientLineId = "line-1",
                    createdAt = "2026-03-06T00:00:00Z",
                    updatedAt = "2026-03-06T00:00:00Z"
                )
            ),
            nameMemory = listOf(
                RememberedEntryName(
                    displayName = "Chickpeas",
                    normalizedName = "chickpeas",
                    sectionId = "pantry",
                    useCount = 3,
                    lastUsedAt = "2026-03-06T00:00:00Z"
                )
            ),
            updatedAt = "2026-03-06T00:00:00Z"
        )

        val encoded = ShoppingListStateCodec.encode(state)
        val decoded = ShoppingListStateCodec.decode(encoded)

        assertEquals(state, decoded)
    }

    @Test
    fun normalize_removes_accents_and_case() {
        val normalized = ShoppingText.normalize("  Crème   FRAÎCHE ")
        assertEquals("creme fraiche", normalized)
    }

    @Test
    fun suggester_returns_typo_tolerant_match() {
        val memory = listOf(
            RememberedEntryName(
                displayName = "Chickpeas",
                normalizedName = "chickpeas",
                sectionId = "pantry",
                useCount = 8,
                lastUsedAt = "2026-03-06T00:00:00Z"
            ),
            RememberedEntryName(
                displayName = "Cinnamon",
                normalizedName = "cinnamon",
                sectionId = "pantry",
                useCount = 2,
                lastUsedAt = "2026-03-06T00:00:00Z"
            )
        )
        val sections = mapOf("pantry" to ShoppingSection(id = "pantry", name = "Pantry", sortOrder = 0))

        val suggestions = ShoppingNameSuggester.suggest(
            memory = memory,
            sectionsById = sections,
            query = "chikpeas",
            limit = 5
        )

        assertTrue(suggestions.isNotEmpty())
        assertEquals("Chickpeas", suggestions.first().name)
        assertEquals("Pantry", suggestions.first().sectionName)
    }
}
