package app.recipebook.data.local.shoppinglist

import java.text.Normalizer
import java.time.Instant
import java.util.UUID
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class ShoppingListState(
    val sections: List<ShoppingSection> = ShoppingDefaults.sections,
    val entries: List<ShoppingListEntry> = emptyList(),
    val nameMemory: List<RememberedEntryName> = emptyList(),
    val updatedAt: String = Time.nowIsoUtc()
)

@Serializable
data class ShoppingSection(
    val id: String,
    val name: String,
    val sortOrder: Int,
    val isBuiltIn: Boolean = false
)

@Serializable
data class ShoppingListEntry(
    val id: String,
    val name: String,
    val amount: String? = null,
    val sectionId: String? = null,
    val checked: Boolean = false,
    val isAutoGenerated: Boolean = false,
    val sourceRecipeId: String? = null,
    val sourceIngredientLineId: String? = null,
    val createdAt: String = Time.nowIsoUtc(),
    val updatedAt: String = Time.nowIsoUtc()
)

@Serializable
data class RememberedEntryName(
    val displayName: String,
    val normalizedName: String,
    val sectionId: String? = null,
    val useCount: Int = 1,
    val lastUsedAt: String = Time.nowIsoUtc()
)

data class NameSuggestion(
    val name: String,
    val sectionId: String?,
    val sectionName: String?,
    val score: Int
)

object ShoppingDefaults {
    val sections: List<ShoppingSection> = listOf(
        ShoppingSection(id = "produce", name = "Produce", sortOrder = 0, isBuiltIn = true),
        ShoppingSection(id = "dairy", name = "Dairy", sortOrder = 1, isBuiltIn = true),
        ShoppingSection(id = "meat", name = "Meat", sortOrder = 2, isBuiltIn = true),
        ShoppingSection(id = "pantry", name = "Pantry", sortOrder = 3, isBuiltIn = true),
        ShoppingSection(id = "frozen", name = "Frozen", sortOrder = 4, isBuiltIn = true),
        ShoppingSection(id = "bakery", name = "Bakery", sortOrder = 5, isBuiltIn = true),
        ShoppingSection(id = "other", name = "Other", sortOrder = 6, isBuiltIn = true)
    )
}

object ShoppingIds {
    fun newId(): String = UUID.randomUUID().toString()
}

object Time {
    fun nowIsoUtc(): String = Instant.now().toString()
}

object ShoppingText {
    fun normalize(input: String): String {
        val withoutAccents = Normalizer.normalize(input, Normalizer.Form.NFD)
            .replace("\\p{M}+".toRegex(), "")
        return withoutAccents
            .lowercase()
            .replace("[^a-z0-9 ]".toRegex(), " ")
            .replace("\\s+".toRegex(), " ")
            .trim()
    }
}

object ShoppingNameSuggester {
    fun suggest(
        memory: List<RememberedEntryName>,
        sectionsById: Map<String, ShoppingSection>,
        query: String,
        limit: Int = 8
    ): List<NameSuggestion> {
        val normalizedQuery = ShoppingText.normalize(query)
        if (normalizedQuery.isBlank()) {
            return memory
                .sortedWith(compareByDescending<RememberedEntryName> { it.useCount }.thenByDescending { it.lastUsedAt })
                .take(limit)
                .map {
                    NameSuggestion(
                        name = it.displayName,
                        sectionId = it.sectionId,
                        sectionName = sectionsById[it.sectionId]?.name,
                        score = 0
                    )
                }
        }

        return memory
            .mapNotNull { item ->
                val score = score(normalizedQuery, item.normalizedName)
                if (score == Int.MAX_VALUE) {
                    null
                } else {
                    NameSuggestion(
                        name = item.displayName,
                        sectionId = item.sectionId,
                        sectionName = sectionsById[item.sectionId]?.name,
                        score = score
                    )
                }
            }
            .sortedWith(
                compareBy<NameSuggestion> { it.score }
                    .thenBy { it.name.length }
                    .thenBy { it.name.lowercase() }
            )
            .take(limit)
    }

    private fun score(query: String, candidate: String): Int {
        if (candidate == query) return 0
        if (candidate.startsWith(query)) return 1
        if (candidate.contains(query)) return 2

        val distance = levenshtein(query, candidate)
        val maxDistance = maxOf(1, query.length / 4)
        return if (distance <= maxDistance) 100 + distance else Int.MAX_VALUE
    }

    private fun levenshtein(a: String, b: String): Int {
        if (a == b) return 0
        if (a.isEmpty()) return b.length
        if (b.isEmpty()) return a.length

        val prev = IntArray(b.length + 1) { it }
        val curr = IntArray(b.length + 1)

        for (i in 1..a.length) {
            curr[0] = i
            for (j in 1..b.length) {
                val cost = if (a[i - 1] == b[j - 1]) 0 else 1
                curr[j] = minOf(
                    curr[j - 1] + 1,
                    prev[j] + 1,
                    prev[j - 1] + cost
                )
            }
            for (j in prev.indices) {
                prev[j] = curr[j]
            }
        }

        return prev[b.length]
    }
}

object ShoppingListStateCodec {
    private val json = Json {
        encodeDefaults = true
        explicitNulls = false
        ignoreUnknownKeys = true
    }

    fun encode(state: ShoppingListState): String = json.encodeToString(ShoppingListState.serializer(), state)

    fun decode(serialized: String): ShoppingListState =
        json.decodeFromString(ShoppingListState.serializer(), serialized)
}
